name: deploy gh-pages

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          node-version: ${{ matrix.node-version }}

      # NPM Install and build
      - name: NPM install
        working-directory: ./
        run: |
          npm install
          npm run build

      # Deploy to GitHub Page branch
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
